### PR TITLE
SWAP: Add dont leave this page on every step

### PR DESCRIPTION
**Pull request by Naggertooth**
# Pull request template

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] branch rebased on `develop`
- [x] styleguide check `npm run validate`
- [x] good naming
- [x] keep simple
- [x] video or screenshot attached
- [x] testing instruction attached
- [x] check your PR once again

### Description

"Пожалуйста, не уходите с этой страницы" на каждый этап свапа #1715

### Video or screenshot

image
image
image

image
image
image
image

### What and how to test

http://pr1747.swaponline.site

### CODE REVIEW

**Comment by noxonsu** [comment]
как то награмождено, я думаю надо перенести прямо в текст текущего шага https://screenshots.wpmix.net/chrome_2019-03-14_06-24-29a1721fd8-ea64-4ee8-9de6-6e5efe76b0d9.png

**Comment by Naggertooth** [comment]
image

image

image

**Comment by noxonsu** [comment]
Лучше

**Comment by Naggertooth** [comment]
image

**Pull request merged**
