### PR TITLE
Bitcoin && Swap currencies pages were crashed and swap-btc swap went wrong

### PR DESCRIPTION
**Pull request by Pasha8914**
# Pull request template

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/swaponline/swap.react/wiki/CONTRIBUTING) guide
- [x] branch rebased on `develop`
- [ ] styleguide check `npm run validate`
- [x] good naming
- [x] keep simple
- [ ] video or screenshot attached
- [x] testing instruction attached
- [x] check your PR once again

### CODE REVIEW

**Comment by noxonsu** [comment]
не понятно что проверять

**Comment by noxonsu** [comment]
https://github.com/swaponline/swap.react/issues/1190

**Comment by noxonsu** [comment]
чето не то. нажимаю на bitcoin vallet и баг с локализоваными урл

**Comment by Pasha8914** [comment]
ломалась страница каренси-валет
image
при нажатии на биткойин и на свап токен
плюс поправил процесс свапа бтс- свап

**Comment by Pasha8914** [comment]
#1192

**Comment by Pasha8914** [comment]
#1190

**Comment by Pasha8914** [comment]
image
image
image

**Comment by nthgness** [comment]
вввв

**Pull request merged**
